version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --workers ${FASTAPI_WORKERS} --reload
    volumes:
      - ./api:/python-mongo-template/api:ro
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
